Update mkdocs.yml
groupplants/docs pull request #21
Opened 2024-01-19 18:05 UTC by Pro100wnick1

Nowy tytuł do mkdocsów

2024-01-19 20:17 UTC, Niviann commented
Weź dodaj jakiś favicon może

2024-01-20 12:01 UTC, olaaaf approved these changes
😇

2024-01-20 12:23 UTC, D-Mielewczyk requested changes
Zmień tytuł MR. Gdybyś nie zmienił w mainie byłby commit o nazwie "Update mkdcos.yml" i nie wiadomo o co z nim chodzi po nazwie. Jak będzie "Zmiana tytułu strony" to od razu wiadomo ocb.

2024-01-20 12:31 UTC, D-Mielewczyk approved these changes

2024-01-20 13:05 UTC, merged