Connectivity sleep schema
groupplants/docs pull request #25
Opened 2024-01-19 20:05 UTC by wojtekszamocki

2024-01-19 21:51 UTC, olaaaf commented
Git, ale waked up to woke up

2024-01-20 12:37 UTC, D-Mielewczyk commented
@olaaaf to nie akcpetuj jak jest błąd!!

2024-01-20 12:37 UTC, D-Mielewczyk requested changes

2024-01-20 12:37 UTC, D-Mielewczyk commented on docs/assets/uml/serwer_klient.png
speeling waked_up -> woke_up

2024-01-20 12:37 UTC, D-Mielewczyk commented on graphor/serwer_klient_sleep.gaphor
same spelling error

2024-01-20 16:18 UTC, wojtekszamocki commented on graphor/serwer_klient_sleep.gaphor
Done in  https://github.com/groupplants/docs/pull/25/commits/660a8fdd3fd6f9296eea81ecf153962a1465fbac

2024-01-20 16:21 UTC, D-Mielewczyk approved these changes

2024-01-21 12:50 UTC, merged